name: 'northwind'
version: '1.0.0'
config-version: 2

profile: 'northwind'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  prueba_api:
    staging:
      +materialized: view
    marts:
      +materialized: view
